#!/bin/bash

#Simple if then statement

read -p "Tell me your favorite color: " color
read -p "Tell me your favorite ice cream flavor: " icecream
read -p "Tell me your favorite pizza topping: " pizza

if [ $color = "green" ]
then
	echo "Nice! $color is a popular color with some nation's flags."
elif [ $color = "red" ]
then
	echo "Nice! Fun fact, $color is the color of the most popular condiment for hot dogs." 
elif [ $color = "blue" ]
then
	echo "Nice! Did you know the sky really isn't $color afterall!"
fi

